### ISSUE TITLE
Unknown error when running createdump

### ISSUE THREAD

**Issue by andtii** [joe-elliott/netcore-kubernetes-profiling#4]
Hey, first of all thank you for the awesome work you have done here to provide all theese guidelines and examples. I followed your example to create a minidump here
https://github.com/joe-elliott/netcore-kubernetes-profiling/blob/master/coredumps/generating.md

First i got a permission denied error when running the createdump and i saw that the securityContext:
      privileged: true
was missing in that sidecar yaml so when i added that it works to run the createdump withou access denied.
But i ran into this unknown error now instead. Do you have any clue what could cause this?
https://github.com/dotnet/coreclr/issues/25152

**Comment by joe-elliott** [comment]
That's interesting.  So the documentation suggests the container needs elevated privileges:

https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md#configurationpolicy

But I was able to run the coredump example without it.  I just assumed it was b/c I was root in the container and I was inspecting processes in the same process namespace.  At one point I had `allowPrivilegeEscalation: true` but removed it b/c I thought it was unnecessary.

Can you post the original permission error you received?

**Comment by joe-elliott** [comment]
Follow up thoughts:

The error code reported in https://github.com/dotnet/coreclr/issues/25152 appears to be `CORDBG_E_UNSUPPORTED`:
https://github.com/dotnet/coreclr/blob/master/src/inc/corerror.xml#L2162

If you're using this against your own application container can you post your yaml?  or Dockerfile that the application was built with?

I'm able to reproduce that error by running the debugging sidecar container against an alpine application image.  I'd definitely like to see how the application container was built that you are running the debugging sidecar against.
```
# /usr/share/dotnet/shared/Microsoft.NETCore.App/2.2.5/createdump 6
Writing minidump with heap to file /tmp/coredump.6
CLRDataCreateInstance(ICLRDataEnumMemoryRegions) FAILED 80131c4e
```

**Comment by andtii** [comment]
@joe-elliott I am running against a alpine container so you have the same behavior as me then.

**Comment by joe-elliott** [comment]
@andtii So there is an alpine version of the container:  https://hub.docker.com/r/joeelliott/netcore-debugging-tools/tags

`joeelliott/netcore-debugging-tools:v0.0.11-2.2.5-alpine`

I've not messed with alpine as much, but I have gotten some of the basic demos working.  If you have the time please try and let me know?

**Comment by joe-elliott** [comment]
Allright, so using this podspec:

```
apiVersion: v1
kind: Pod
metadata:
  name: sample-netcore-app
  labels:
    app: sample-netcore-app
spec:
  shareProcessNamespace: true
  containers:
  - name: sample-netcore-app
    image: joeelliott/sample-netcore-app:v1.0.0-2.2.5-alpine
    imagePullPolicy: IfNotPresent
    env:
    - name: COMPlus_DbgEnableMiniDump
      value: "1"
    - name: COMPlus_DbgMiniDumpName
      value: "/tmp/coredump.%d"
    - name: ASPNETCORE_URLS
      value: http://*:8080
    volumeMounts:
    - mountPath: /tmp
      name: tmp
  - name: profile-sidecar
    image: joeelliott/netcore-debugging-tools:v0.0.11-2.2.5-alpine
    imagePullPolicy: IfNotPresent
    args:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: /tmp
      name: tmp
  volumes:
  - name: tmp
    emptyDir: {}
```
I was able to generate a coredump from an alpine sidecar:
```
~ # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /pause
   10 root      0:00 dotnet /app/sample-netcore-app.dll
   17 root      0:00 sleep 3600
   45 root      0:00 ash
  130 root      0:00 ps aux
~ # /usr/share/dotnet/shared/Microsoft.NETCore.App/2.2.5/createdump 10
Writing minidump with heap to file /tmp/coredump.10
Written 42733568 bytes (10433 pages) to core file
```
I am having issues with lldb, but it's a start.
